language: python
dist: xenial
python:
  - "3.5"
addons:
  apt:
    packages:
    - enchant

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - python setup.py install
  - pip install codecov
  - pip install twine
  - pip install flake8
  - python -m nltk.downloader stopwords
  - make word2vec/arwiki-20191201-learned_vectors.50_cell.10k.kv
  - make word2vec/cswiki-20191201-learned_vectors.50_cell.10k.kv
  - make word2vec/enwiki-20191201-learned_vectors.50_cell.10k.kv
  - make word2vec/kowiki-20191201-learned_vectors.50_cell.10k.kv
  - make word2vec/viwiki-20191201-learned_vectors.50_cell.10k.kv

script:
  - flake8 . --ignore=E722
  - coverage run --source drafttopic -m pytest -m "not nottravis"
  - sphinx-build -anW -b html docs dist/docs
  - sphinx-build -b linkcheck docs dist/docs

after_success:
  - coverage report
  - codecov

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
